server:
  port: 8080
  error:
    whitelabel:
      enabled: false

api-version: v1

root-user:
  password: password

file-storage:
  root-dir: "upload"

redis:
  host: localhost
  port: 6379
  password: password

jwt:
  access-token-expiration-ms:  60000
  refresh-token-expiration-ms: 3600000
  access-token-secret: signingkey
  refresh-token-secret: singingkey
  authorities-key: roles
  token-prefix: Bearer
  header-string : Authorization

data:
  sort-dir: "asc"
  page-size: 20
  job:
    sort-by: title
  model:
    sort-by: firstName
  option:
    sort-by: title
  reminder:
    sort-by: title
  user:
    sort-by: firstName
  client:
    sort-by: name

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: internalServices
  datasource:
    username: 'jimmodel'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/jimmodel
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  web:
    resources:
      add-mappings: false
